name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: test
      run: ls
    - name: Restore dependencies
      run: cd AvalonStudio/AvalonStudio && dotnet restore
    - name: Build
      run: cd AvalonStudio/AvalonStudio && dotnet build --no-restore
